apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: queue-housekeeping-cronjob
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: retryalldlqs
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl -XPUT http://case-notes-to-probation/queue-admin/retry-all-dlqs
          restartPolicy: Never
